main.go

I made `user-agent` configurable while its default value is the same as before `grpc_health_probe`.
If there is any concern, please let me know

make user-agent configurable

---

Dockerfile

To fix CVEs and have it up to date in general.

Bump Docker base image to golang:1.13

---

main.go

os.Exit() calls in main() are causing `defer` statements to be ignored.
This surfaced in several bug reports (such as Java gRPC servers) as health
RPCs causing stack traces or "broken pipe" errors.
Fixes #34.
Fixes #33.

Close connection before exiting

---

README.md

I'm using your tool and had to go to main to find the server flag. Thought a documentation update with the other flags you've built in would be useful to others.

Documentation update: Added other available flags

---

.github/workflows/release.yml
.goreleaser.yml
go.mod
go.sum

Adding darwin/{amd64,arm64} builds for releases.
Adding container image (via ghcr.io) tagged and pushed on each
release, containing a single binary. Currently only for linux/amd64.
Closes #61.

Add darwin builds + linux container image

---

main.go

`rpcCtx` created with the `rcp-timeout` is being overwritten incorrectly by
the metadata context, making the timeout being ignored for the RPC call.

Fix rpc-timeout not being used correctly

---

.github/workflows/ci.yml
.github/workflows/release.yml
.goreleaser.yml
.ko.yaml

This is an alternative take to #86.
Fixes #85.
- Example multi-arch repo: https://github.com/ahmetb/grpc-health-probe/pkgs/container/grpc-health-probe/9380802?tag=v0.99.10
- Build output: https://github.com/ahmetb/grpc-health-probe/runs/4005113125?check_suite_focus=true
advantages:
* no Dockerfile
* multi-arch images can be built/pushed in one command.
* reproducible builds as they are timestamped to 0.
disadvantages:
* limited to os/arch combonatios supported on the base
image (gcr.io/distroless/static:nonroot) and linux/386
is currently not published on distroless.
* binaries are compiled twice
* produced binaries in GH releases vs container images
are not identical (there's visible size diff, needs debugging)
* can't use OCI labels such as `org.opencontainers.image.source`
but they are …

add multi-arch images using ko

---

README.md

This PR adds complementary documentation to https://github.com/grpc-ecosystem/grpc-health-probe/pull/72
Ping @ahmetb @drigz @farzadmf

docs: adds documentation for RPC headers.

---

.github/workflows/ci.yml
Dockerfile
go.mod
go.sum

Bump go to 1.18 to resolve vulnerability - [CVE-2022-27191](https://nvd.nist.gov/vuln/detail/CVE-2022-27191)

Upgrade go to 1.18 to resolve security vulnerability CVE-2022-27191

---

README.md

- version in manual installation part has updated to `v0.4.13`
- deprecated installation method `get` is replaced with recent way `install`.

updated: version and installation method

---

go.mod
go.sum

golang.org/x/text must be updated to fix CVE-2022-32149
Scan from Trivy:
Library: golang.org/x/text
Vulnerability: CVE-2022-32149
Severity: MEDIUM
Installed version: v0.3.7
Fixed Version: v0.3.8
Title: golang: golang.org/x/text/language: ParseAcceptLanguage takes a long time to parse complex tags

Update golang.org/x/text to fix CVE-2022-32149

---

.github/workflows/ci.yml
README.md
main.go

Added `-version` flag.  Exits non-zero so accidentally running with this flag will not indicate a service is up. 
Typical output:
```
$ ./grpc-health-probe -version
git b35a00f4192e0a0654c9e1ff6e7400513e2d000a 2023-06-13T04:13:12Z
```
When built when there are local changes not checked into Git:
```
$ ./grpc-health-probe -version
git 1089f40639043ee46cc47cbea1bcb0cc48cfc284 2023-06-12T16:41:19Z (built with changes outside version control)
```
When not built with VCS information:
```
$ go run main.go -version
vcs info was not included in build
exit status 5
```
Note, Go does not include the Git tag in the build information included in the executable.  If we want to do something like that, in the past I have had a build job run a script that runs `git` commands and writes the output into …

Add -version flag

---

.github/workflows/ci.yml
.github/workflows/release.yml

Migrate to goreleaser-action@v5.

chore: Use goreleaser-action@v5

---

.gitignore

fixes #159 
tested locally by running 
````
goreleaser release --snapshot --clean
````
before and after aplying this change:
<details>
<summary>before</summary>
````bash
~/grpc-health-probe|fix-drity-build ⇒  git checkout master                                     
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
~/grpc-health-probe|master⚡ ⇒  goreleaser release --snapshot --clean                         
• starting release...
• loading config file                              file=.goreleaser.yml
• loading environment variables
• getting and validating git state
• building...                                    commit=992bb35f76c2b7f3835ccbdafdbe77527717c9a1 latest tag=v0.4.21
• pipe skipped                                   reason=disabled during snapshot mode …
```

Fix dirty build flag in release binaries

---

.github/workflows/release.yml

Recent releases https://github.com/grpc-ecosystem/grpc-health-probe/releases are misleading, because they are erroneously only listing the one latest change of the last commit, often just some chore task after more significant changes.
Goreleaser requires full git history to generate full changelog.
See
* https://goreleaser.com/errors/no-history/
* https://goreleaser.com/ci/actions/
Please consider manually changing or generating release notes for at least few recent releases or adding compare links.

Fix missing changelog entries on releases

---

.github/workflows/release.yml
.goreleaser.yml
.ko.yaml
main.go

Improves upon #146 to include the semantic version number from git tag.

Add semantic version from git tag

---

README.md

Now that k8s supports liveness checks using grpc, we need to mention this in the README.

Mention official feature in `README.md`

---

.github/workflows/tag-release.yml

This will automatically bump a patch version every time we merge a commit into master. Then goreleaser will prepare a release for the tag.

Auto-tag commits on master

---

.github/workflows/ci.yml
.github/workflows/release.yml
go.mod

The CVE is already fixed in the latest version, 0.4.34. This proliferates the go version found in the Dockerfile of 1.23 to the other parts of the repo like go.mod, and the github CI files.

Sync golang upgrade to 1.23 to all other files

---

.goreleaser.yml

Noticed the warnings in action logs.
Before:
```
$ goreleaser check
• only  version: 2  configuration files are supported, yours is  version: 0 , please update your configuration
• checking                                 path=.goreleaser.yml
• DEPRECATED:  archives.format  should not be used anymore, check https://goreleaser.com/deprecations#archivesformat for more info
• .goreleaser.yml                                  error=configuration is valid, but uses deprecated properties
⨯ command failed                                   error=1 out of 1 configuration file(s) have issues
```
After:
```
$ goreleaser check
• checking                                 path=.goreleaser.yml
• 1 configuration file(s) validated
• thanks for using GoReleaser!
```

Updated deprecated goreleaser config

---

.github/workflows/ci.yml
.github/workflows/release.yml
.goreleaser.yml
.ko.yaml

* Use https://goreleaser.com/customization/ko/ instead of additional github action and a separate config file.
* Same platforms as before.
* Base image changed from `gcr.io/distroless/static` to `gcr.io/distroless/static:nonroot` as there should be no need for root privileges.
* ~Added mutable `latest` tag to released image to ease referencing it. Question for @ahmetb: Do we want to keep that?~ REVERTED
* Software bill of material ([SBOM](https://www.cisa.gov/sbom)) published in [SPDX](https://spdx.dev/) format along with container images
* Tighter workflow permissions
* Disabled Go build cache for releases
Test release in my fork:
* https://github.com/stefanb/grpc-health-probe/releases/tag/v0.4.39-stefanb-dev11
* https://ghcr.io/stefanb/grpc-health-probe (compare it with …

Move ko container image builds to goreleaser

---

README.md

* Use `TARGETOS` & `TARGETARCH` implicit variables to choose correct release binary for any supported target ([docs](https://docs.docker.com/build/building/variables/#multi-platform-build-arguments))
* Added a simpler option to `COPY --from=ghcr.io/grpc-ecosystem/grpc-health-probe:v0.4.38` ([docs](https://docs.docker.com/reference/dockerfile/#copy))

docs: Improve Dockerfile installation instructions

---

go.mod

Go 1.24.8 has security updates:
https://groups.google.com/g/golang-announce/c/4Emdl2iQ_bI

Bump Go toolchain from 1.24.7 to 1.24.8
